version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    container_name: postgres
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: iwanttobeataco/kittygram_backend:latest
    container_name: backend
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: iwanttobeataco/kittygram_frontend:latest
    container_name: frontend
    volumes:
      - static:/app/result_build/
    depends_on:
      - backend

  gateway:
    image: iwanttobeataco/kittygram_gateway:latest
    container_name: gateway
    ports:
      - "9000:80"
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - backend
      - frontend