server {
    listen 80;
    server_tokens off;

location /api/ {
    proxy_pass http://backend:8000;
    proxy_set_header Host $host:$server_port;
    proxy_set_header X-Forwarded-Host $host:$server_port;
}

location /admin/ {
    proxy_pass http://backend:8000;
    proxy_set_header Host $host:$server_port;
    proxy_set_header X-Forwarded-Host $host:$server_port;
}

    location /media/ {
        alias /media/;
    }

    location / {
        root /staticfiles/;
        index index.html index.htm;
        try_files $uri $uri/ /index.html =404;
    }
}
